travis:
  secure:
    BINSTAR_TOKEN: HUUA/3/if7Wqy1Q4uMliQYHt9ka+ZjgZxmPmsVx+DFINN3Rpkd1Uyyq9fgHEGgy7Zo1W+K5AK/MgFh2aN9rudmcAkB4AiUq3ib4pIPR6fKEJk+uVjwFSKCnBNrZrHqxRXR1nGU/BftVLroTe6DCtYD2M8eEEmC4rsWFeAPiy4lekifr7JJSqYXbC55tqj+8HDDXmMw416ZSzAFBO/00cnD8KkKuVITpvL/6nSfw33E8Jr6j+mHnYdE+UzAru9mtO3JdzNWAb9InOZBihJqq1rcwtssT37EmY9xjhlmF2VszYeC6BAAg9sTq7HKoT8iA3o0q10/6SISLZ6KbSIL+ZUGQFdvNf/Uo/FaYriDSg7hfehPvvodjqud2T8qs0i+nvDfhj2WzzPKw5sZL9+ZV+ReSlAfFuoFv4jobEDjeauPLWbdF/RHldQHPguQJa6MrJXuT5RBZQgK2GatWKMmvGVn0sQrYRT+Bhl8RQo/CtTY4yrtjBfFiYCbz7JGS+faVjfIai+xFJ6cbSDhRJ821rT0veGI9CR9H6ZckqCgRDztYUu9n9cYs9QQgBMTT00A3N3hNhe4szNGT9O2fruKA7wlIwVFvXEP/mKHzcPRswznq+EBPRmfdYGOOZSsbEbUrtkZHPIswJaMapLoxcj+Qw1WPNjbkY9AefUSJejCbiSeQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
